add: Major changes
- Support document/delete
- Improve basic document styling (make textarea fit whole screen without
  scrollbar)
- Better separation of business logic

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -91,6 +91,29 @@ bake.assert_cmd() {
 	fi
 }
 
+# @description Determine if a flag was passed as an argument
+# @arg $1 string Flag name to test for
+# @arg $@ string Rest of the arguments to search through
+bake.has_flag() {
+	local flag_name="$1"
+
+	if [ -z "$flag_name" ]; then
+		bake.die "Argument must not be empty"
+	fi
+	if ! shift; then
+		bake.die 'Failed to shift'
+	fi
+
+	local arg=
+	for arg; do
+		if [ "$arg" = "$flag_name" ]; then
+			return 0
+		fi
+	done; unset -v arg
+
+	return 1
+}
+
 # @description Change the behavior of Bake. See [guide.md](./docs/guide.md) for details
 # @arg $1 string Name of config property to change
 # @arg $2 string New value of config property
@@ -178,11 +201,17 @@ __bake_trap_debug() {
 # @exitcode 1 if should not print color
 # @internal
 __bake_is_color() {
-	if [[ -v NO_COLOR || $TERM == dumb ]]; then
+	local fd="1"
+
+	if [[ ${NO_COLOR+x} || "$TERM" = 'dumb' ]]; then
 		return 1
-	else
+	fi
+
+	if [ -t "$fd" ]; then
 		return 0
 	fi
+
+	return 1
 }
 
 # @description Calls `__bake_internal_error` and terminates with code 1
@@ -318,7 +347,6 @@ __bake_parse_args() {
 	unset REPLY; REPLY=
 	local -i total_shifts=0
 
-	# FIXME: bug for when passing -v to child task argument
 	local __bake_arg=
 	for arg; do case $arg in
 	-f)
@@ -348,6 +376,10 @@ __bake_parse_args() {
 		if ! shift; then
 			__bake_internal_die 'Failed to shift'
 		fi
+		;;
+	*)
+		break
+		;;
 	esac done
 
 	if [ -n "$BAKE_FILE" ]; then
